MAPA_NOMES = {
    "$ident": "VAR",
    "ident": "IDENT",
    "numero_real": "NUMERO_REAL",
    "floatval(readline());": "FLOATVAL",
    "EOF": "$",
    ";": "PV",           
    "=": "ATRIB",        
    ",": "VIRG",
    ".": "PONTO",
    
    "(": "ABRE_P",
    ")": "FECHA_P",
    "{": "ABRE_C",       
    "}": "FECHA_C",  
    "+": "SOMA",
    "-": "SUB",
    "*": "MULT",
    "/": "DIV",

    ">": "MAIOR",
    "<": "MENOR",
    ">=": "MAIOR_IGUAL",
    "<=": "MENOR_IGUAL",
    "==": "IGUAL",
    "!=": "DIFERENTE"
}


FOLLOW = {
    "<programa>": ["$"],
    "<corpo>": ["PHP_CLOSE"], 
    "<dc>": ["VAR", "ECHO", "IF", "WHILE"],
    "<dc_v>": ["VAR", "FUNCTION", "ECHO", "IF", "WHILE"],
    "<dc_f>": ["VAR", "ECHO", "IF", "WHILE"],
    "<comandos>": ["PHP_CLOSE", "FECHA_C"], 
    "<comando>": ["VAR", "ECHO", "IF", "WHILE", "PHP_CLOSE", "FECHA_C"],
    "<mais_dc>": ["VAR", "ECHO", "IF", "WHILE"],
    "<atribuicao_opcional>": ["VAR", "FUNCTION", "ECHO", "IF", "WHILE"],
    "<expressao>": ["PV", "VIRG", "DIFERENTE", "MENOR", "MENOR_IGUAL", "IGUAL", "MAIOR", "MAIOR_IGUAL", "FECHA_P"],
    "<termo>": ["SOMA", "SUB", "PV", "VIRG", "DIFERENTE", "MENOR", "MENOR_IGUAL", "IGUAL", "MAIOR", "MAIOR_IGUAL", "FECHA_P"],
    "<op_un>": ["VAR", "ABRE_P", "NUMERO_REAL"],
    "<parametros>": ["ABRE_C"],
    "<lista_par>": ["FECHA_P"],
    "<mais_par>": ["FECHA_P"],
    "<corpo_f>": ["FECHA_C"],
    "<dc_loc>": ["VAR", "ECHO", "IF", "WHILE"],
    "<mais_dcloc>": ["VAR", "ECHO", "IF", "WHILE"],
    "<lista_arg>": ["PV"],
    "<argumentos>": ["FECHA_P"],
    "<mais_ident>": ["FECHA_P"],
    "<mais_comandos>": ["PHP_CLOSE", "FECHA_C"],
    "<restoIdent>": ["PV"],
    "<condicao>": ["FECHA_P"],
    "<relacao>": ["VAR", "ABRE_P", "SUB", "FLOATVAL", "NUMERO_REAL"],
    "<outros_termos>": ["PV", "VIRG", "DIFERENTE", "MENOR", "MENOR_IGUAL", "IGUAL", "MAIOR", "MAIOR_IGUAL", "FECHA_P"],
    "<op_ad>": ["VAR", "ABRE_P", "SUB", "NUMERO_REAL"],
    "<fator>": ["MULT", "DIV", "SOMA", "SUB", "PV", "VIRG", "DIFERENTE", "MENOR", "MENOR_IGUAL", "IGUAL", "MAIOR", "MAIOR_IGUAL", "FECHA_P"],
    "<mais_fatores>": ["SOMA", "SUB", "PV", "VIRG", "DIFERENTE", "MENOR", "MENOR_IGUAL", "IGUAL", "MAIOR", "MAIOR_IGUAL", "FECHA_P"],
    "<op_mul>": ["VAR", "ABRE_P", "NUMERO_REAL"],
    "<pfalsa>": ["VAR", "ECHO", "IF", "WHILE", "PHP_CLOSE", "FECHA_C"]
}


REGRAS_NUMERADAS = [
    ("S'", 1),
    ("<programa>", 3), 
    ("<corpo>", 2),  
    ("<dc>", 2),      
    ("<dc>", 1),       
    ("<dc>", 0),     
    ("<mais_dc>", 1),  
    ("<mais_dc>", 0),  
    ("<dc_v>", 2),    
    ("<atribuicao_opcional>", 3), 
    ("<atribuicao_opcional>", 1), 
    ("<dc_f>", 6),    
    ("<parametros>", 3), 
    ("<parametros>", 2),
    ("<lista_par>", 2), 
    ("<mais_par>", 3),   
    ("<mais_par>", 0),   
    ("<corpo_f>", 2),   
    ("<dc_loc>", 2),    
    ("<dc_loc>", 0),     
    ("<mais_dcloc>", 1), 
    ("<mais_dcloc>", 0), 
    ("<comandos>", 2),   
    ("<mais_comandos>", 1), 
    ("<mais_comandos>", 0), 
    ("<comando>", 5),    
    ("<comando>", 8),    
    ("<comando>", 7),    
    ("<comando>", 3),    
    ("<restoIdent>", 2), 
    ("<restoIdent>", 1), 
    ("<pfalsa>", 4),     
    ("<pfalsa>", 0),     
    ("<condicao>", 3),   
    ("<relacao>", 1),   
    ("<relacao>", 1),    
    ("<relacao>", 1),    
    ("<relacao>", 1),    
    ("<relacao>", 1),    
    ("<relacao>", 1),    
    ("<expressao>", 6),  
    ("<expressao>", 2),  
    ("<outros_termos>", 3), 
    ("<outros_termos>", 0), 
    ("<op_ad>", 1),      
    ("<op_ad>", 1),      
    ("<termo>", 3),      
    ("<op_un>", 1),      
    ("<op_un>", 0),      
    ("<mais_fatores>", 3), 
    ("<mais_fatores>", 0), 
    ("<op_mul>", 1),     
    ("<op_mul>", 1),     
    ("<fator>", 1),      
    ("<fator>", 1),      
    ("<fator>", 3),      
    ("<lista_arg>", 3),  
    ("<lista_arg>", 2),  
    ("<argumentos>", 2), 
    ("<mais_ident>", 3), 
    ("<mais_ident>", 0),
    ("<expressao>", 1),   
    ("<comando>", 3),     
]